name: calculator_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.5"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  async: ^2.8.2
  csv: ^5.0.1
  http: ^0.13.4
  badges: ^2.0.3
  http_client_helper: ^2.0.3
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4  # android ios
  desktop_webview_window: ^0.1.6
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.6.3   #https://pub.dev/packages/dropdown_button2
  flutter_email_sender: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/txt/HoldingTax_description.txt
    - assets/txt/HoldingTax_precaution.txt
    - assets/images/new_logo.jpg
    - assets/images/new_logo2.jpg
    - assets/images/tax_consulting_illustration.jpg
    - assets/capgain/firstFilter.CSV
    - assets/images/homepage_image.png
    - assets/images/homepage_image2.png
    - assets/images/consultant_line.png
    - assets/images/
    - assets/images/logo_color_col.png
    - assets/images/logo_color_row.png
    - assets/images/psychology.png
    - assets/images/calculate.png
    - assets/capgain/AcquisitionDate.CSV


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: One_Mobile
      fonts:
        - asset: fonts/ONE Mobile Bold.ttf
          weight: 700  #w700 bold
        - asset: fonts/ONE Mobile Light.ttf
          weight: 300  #w300 light
        - asset: fonts/ONE Mobile Regular.ttf
          weight: 400 #w300 normal
        - asset: fonts/ONE Mobile Title.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
